import type { PracticeTest } from './types'

export const TEST_4: PracticeTest = {
  id: 't4',
  n: 4,
  title: 'Brands and Generics',
  blurb:
    'A full sitting under interview conditions: reason out loud, commit to an answer, then check what you actually said.',
  items: [
    /* ---------------- recall ---------------- */
    {
      shell: 'S01',
      kind: 'mc',
      stem: 'A dental clinic chain wants to know what it owns and what it owes on the last day of June. Which statement answers that, and what stretch of time does it cover?',
      choices: [
        'The income statement, covering the half year to June',
        'The balance sheet, describing the position on that day',
        'The cash flow statement, covering the half year to June',
      ],
      answer: 1,
      why: 'What a business owns and owes is a position, so only the statement frozen on one date can report it. The other two summarise a stretch of time and say nothing about what is left standing at the end of it.',
      traps: {
        0: 'You picked this if you think a profit figure tells you what the clinics own.',
        2: 'You picked this if you are reading the bank account as the list of things owned.',
      },
      rule: 'Ask whether the question is about a period or a single moment before you pick a statement.',
    },
    {
      shell: 'S02',
      kind: 'mc',
      stem: 'A pet-food company takes an order in February, ships the kibble in March, and is paid by the supermarket in May. Under accrual accounting, when does the revenue land on the income statement?',
      choices: [
        'February, when the supermarket placed the order',
        'March, when the kibble was handed over',
        'May, when the cash reached the bank',
      ],
      answer: 1,
      why: 'You have earned the money at the point you have done the thing you were paid for, which here is delivering the kibble. The order is a promise and the payment is a separate cash event, tracked on the cash flow statement.',
      traps: {
        0: 'You picked this if you treat a signed order as earned revenue before anything is delivered.',
        2: 'You picked this if you are booking revenue on a cash basis, the moment money lands.',
      },
      rule: 'Book the sale when you deliver the goods, not when you are ordered and not when you are paid.',
    },
    {
      shell: 'S03',
      kind: 'mc',
      stem: 'You want to judge whether a razor company actually makes money on the thing it sells, before head-office costs and financing get involved. Which margin do you read?',
      choices: [
        'Gross margin, after the direct cost of the product',
        'Operating margin, after the cost of running the company',
        'Net margin, after interest and tax are deducted',
      ],
      answer: 0,
      why: 'Gross margin subtracts only what it cost to make the thing, so it is the one number that describes the product rather than the company wrapped around it. Everything lower down mixes in overhead, borrowing, and the tax rate.',
      traps: {
        1: 'You picked this if you are judging the whole business when the question was about the product.',
        2: 'You picked this if you let the debt load and the tax rate colour a question about a razor.',
      },
      rule: 'Gross margin judges the product, operating margin the business, net margin the capital structure.',
    },
    {
      shell: 'S04',
      kind: 'mc',
      stem: 'A soft-drink company has raised its price about 4% a year for a decade, and shoppers still reach past the cheaper store-label cola for its can. Which moat is that?',
      choices: [
        'Intangible assets, since the name itself carries the price',
        'Switching costs, since changing colas is costly for shoppers',
        'Efficient scale, since the market supports one cola maker',
      ],
      answer: 0,
      why: 'The evidence is price held above an identical substitute for ten years, and what the shopper is paying the extra for is the name on the can. Nothing physical or contractual stops them buying the store label tomorrow.',
      traps: {
        1: 'You picked this if you call any repeat purchase a switching cost; swapping cans costs a shopper nothing.',
        2: 'You picked this if you treat a large incumbent as proof the market only fits one player.',
      },
      rule: 'Name the moat from the evidence in front of you, not from how big the company is.',
    },
    {
      shell: 'S05',
      kind: 'mc',
      stem: 'A pharmacy chain earns 6% on the capital it puts into new stores, and that capital costs it 9%. Management now plans to double the rate at which it opens stores. What happens to value?',
      choices: [
        'Value falls faster, because each new store earns below its cost',
        'Value rises with scale, because fixed costs spread over more stores',
        'Value is unchanged, because growth and returns offset each other',
      ],
      answer: 0,
      why: 'Each dollar committed to a 6% store funded at 9% loses three cents a year for as long as it stays there. Opening faster is not a different decision, it is the same losing trade done more times.',
      traps: {
        1: 'You picked this if you assume scale rescues a return problem; the 6% already reflects how the stores run.',
        2: 'You picked this if you treat growth as neutral rather than as capital being committed to something.',
      },
      rule: 'Growth creates value only when the return on capital beats the cost of that capital.',
    },
    {
      shell: 'S06',
      kind: 'mc',
      stem: 'You are buying a medical device distributor outright. Why does the cash sitting in its bank account get subtracted when you work out enterprise value?',
      choices: [
        'Because you receive that cash, cutting what the operations cost',
        'Because cash is idle and does nothing while it sits there',
        'Because cash belongs to the lenders before shareholders see it',
      ],
      answer: 0,
      why: 'The day the deal closes you own the bank balance too, so it comes straight back off the effective price of the operating business. Enterprise value is meant to price the operations alone, free of how they were financed.',
      traps: {
        1: 'You picked this if you think cash is excluded for being idle rather than for becoming yours.',
        2: 'You picked this if you have merged the cash adjustment with the order in which claims get paid.',
      },
      rule: 'Subtract cash because you get it back, not because it is doing nothing.',
    },
    {
      shell: 'S07',
      kind: 'mc',
      stem: 'Two risks face a generic drug maker: it could lose its single largest customer, and a recession could cut drug volumes across the whole economy. Which risk does CAPM say investors are paid to bear?',
      choices: [
        'The recession risk, which every diversified holder still carries',
        'The customer risk, which is the bigger threat to profit',
        'The customer risk, which pushes the company beta higher',
      ],
      answer: 0,
      why: 'You are compensated only for what you cannot escape by owning other things. One lost contract washes out against the rest of a portfolio, while a recession arrives in every holding at once and nobody can step aside from it.',
      traps: {
        1: 'You picked this if you assume the largest risk you can name is the one that gets paid for.',
        2: 'You picked this if you read beta as company-specific trouble rather than as movement with the market.',
      },
      rule: 'Ask whether a risk would still hurt someone who owned everything; if not, nobody pays you to carry it.',
    },
    {
      shell: 'S08',
      kind: 'mc',
      stem: "You sell a call option on a pet-food company's shares and collect a $2 premium. What have you taken on by doing that?",
      choices: [
        'An obligation to sell, with your gain capped at the premium',
        'A right to sell, with your loss capped at the premium',
        'An obligation to sell, with your loss capped at the premium',
      ],
      answer: 0,
      why: 'The $2 is the whole of your upside, and you handed the buyer the choice of whether the contract ever gets used. If the shares run, you still deliver at the strike and wear the difference.',
      traps: {
        1: 'You picked this if you swapped the two sides; the premium bought someone else the right, not you.',
        2: "You picked this if you gave the seller the buyer's capped loss. A rising share price has no ceiling, so the seller's loss has none either.",
      },
      rule: 'The option buyer holds the right; the seller holds the obligation and the open-ended loss.',
    },

    /* ---------------- apply ---------------- */
    {
      shell: 'S09',
      kind: 'num',
      stem: "A pharmacy chain's depreciation charge rises by $20M. The tax rate is 25% and nothing else changes. By how much does cash from operations rise, in $M?",
      answer: 5,
      unit: '$M',
      format: 'Answer as a number, e.g. 8',
      work: [
        { label: 'Operating profit falls by the charge', value: '($20M)', running: 'operating profit ($20M)' },
        { label: 'Tax saved at 25%', value: '+$5M', running: 'net income ($15M)' },
        { label: 'Add back depreciation, no cash moved', value: '+$20M', running: 'cash from operations +$5M' },
      ],
      why: 'Cash rises while profit falls, because the charge itself never touched the bank but the tax it saved is real money. The $5M is exactly that tax saving.',
      rule: 'A non-cash charge costs you no cash and still hands you the tax saving on it.',
    },
    {
      shell: 'S10',
      kind: 'num',
      stem: 'A medical device distributor reports $30M of net income. Depreciation is $6M, receivables rise $12M, inventory rises $9M, and payables are unchanged. What is cash from operations, in $M?',
      answer: 15,
      unit: '$M',
      format: 'Answer as a number, e.g. 22',
      work: [
        { label: 'Net income', value: '+$30M', running: '+$30M' },
        { label: 'Add back depreciation', value: '+$6M', running: '+$36M' },
        { label: 'Receivables rise, sales not collected', value: '($12M)', running: '+$24M' },
        { label: 'Inventory rise, stock paid for', value: '($9M)', running: '+$15M' },
      ],
      why: 'Most of the reported profit is sitting in a warehouse and in invoices hospitals have not paid, which is why only half of it reached the bank. A growing distributor consumes cash on the way up, before any of it comes back.',
      rule: 'When receivables or inventory grow, subtract the increase: that cash is tied up, not banked.',
    },
    {
      shell: 'S11',
      kind: 'num',
      stem: 'A soft-drink company has a market cap of $900M, debt of $250M, and cash of $50M. EBITDA is $220M. What EV/EBITDA multiple is it trading at?',
      answer: 5,
      unit: 'x',
      format: 'Answer as a number, e.g. 11',
      work: [
        { label: 'Equity value, the market cap', value: '+$900M', running: '$900M' },
        { label: 'Add debt', value: '+$250M', running: '$1,150M' },
        { label: 'Subtract cash', value: '($50M)', running: '$1,100M' },
        { label: 'Divide by EBITDA', value: '/ $220M', running: '5.0x' },
      ],
      why: 'EBITDA is earned before lenders take their interest, so it belongs to the whole business and has to sit under enterprise value. Put a shareholders-only numerator over it and two identical businesses with different debt will look differently priced.',
      rule: 'Match the top to the bottom: enterprise value over EBITDA, share price over earnings.',
    },
    {
      shell: 'S12',
      kind: 'num',
      stem: 'A razor company sells a cartridge pack at $10 with $6 of variable cost. It cuts the price by 10% and the cost per pack does not move. What percent volume increase keeps gross profit flat?',
      answer: 33,
      tol: 1,
      unit: '%',
      format: 'Round to the nearest whole number, e.g. 20',
      work: [
        { label: 'Gross profit per pack at $10', value: '+$4.00', running: '$4.00' },
        { label: 'Price falls 10%, cost unchanged', value: '($1.00)', running: '$3.00' },
        { label: 'Volume ratio needed, 4.00 over 3.00', value: '1.33x', running: '1.33x' },
        { label: 'Extra volume required', value: '+33%' },
      ],
      why: 'A tenth off the price took a quarter of the profit, because the cost did not fall with it. The thinner the gross margin, the more brutal that arithmetic gets.',
      rule: 'A price cut comes straight out of gross profit, so it needs far more volume than it looks.',
    },
    {
      shell: 'S13',
      kind: 'num',
      stem: "A pet-food company's sales grow 12% a year while inflation runs at 3%. Using the rule of 72, roughly how many years does it take for real sales to double?",
      answer: 8,
      tol: 0.5,
      unit: ' years',
      format: 'Answer as a number, e.g. 14',
      work: [
        { label: 'Nominal sales growth', value: '+12%' },
        { label: 'Less inflation', value: '(3%)', running: '+9% real' },
        { label: 'Rule of 72, 72 divided by 9', value: '8', running: '8 years' },
      ],
      why: 'Doubling the tins going out of the door is the achievement; doubling the dollar figure can just be prices rising alongside everything else. Strip inflation out first and the growth claim starts to mean something.',
      rule: 'Take inflation out before you compound, or you will double the dollars and not the business.',
    },
    {
      shell: 'S14',
      kind: 'mc',
      stem: 'A dental clinic chain reports $9M of net income for the year, pays no dividend, and issues no shares. Which balance sheet line must rise by exactly $9M?',
      choices: [
        "Cash in the bank, where the year's profit ends up",
        'Retained earnings, where profit kept in the business collects',
        'Total assets, which grow by the profit the year produced',
      ],
      answer: 1,
      why: 'Net income has one guaranteed destination on the balance sheet and it is the owner side. Where the matching asset turns up depends on what the clinics did with the money, and these figures do not tell you.',
      traps: {
        0: 'You picked this if you route net income into the bank balance; accruals break that link.',
        2: 'You picked this if you forget that assets can fall elsewhere, for instance when debt is repaid.',
      },
      rule: 'Profit not paid out lands in retained earnings; where the cash went is a separate question.',
    },
    {
      shell: 'S15',
      kind: 'mc',
      stem: 'A generic drug maker spends heavily and continuously on its manufacturing plants simply to keep producing. Which multiple compares it most fairly against its peers?',
      choices: [
        'EV/EBIT, which charges it for the assets it consumes',
        'EV/EBITDA, which sidesteps differences in the depreciation policy',
        'P/E, which shows what the shareholders are left with',
      ],
      answer: 0,
      why: 'Adding depreciation back flatters a company whose plants really do wear out and really do get replaced. Charging for that consumption is what stops the multiple pretending the capital spending is optional.',
      traps: {
        1: 'You picked this if you read depreciation as an accounting choice rather than a bill. These plants really are replaced, so adding the charge back prices them at nothing.',
        2: 'You picked this if you let debt load and tax rate into what should be an operations comparison.',
      },
      rule: 'The heavier and more real the capital spending, the more you should charge for it before comparing.',
    },
    {
      shell: 'S16',
      kind: 'mc',
      stem: 'Rates rise by one percentage point. Rank the damage across a thirty-year government bond, a mature pharmacy chain, and a loss-making pet-food startup whose profits are years away.',
      choices: [
        'Startup worst, then the long bond, then the pharmacy chain',
        'Long bond worst, then the startup, then the pharmacy chain',
        'Pharmacy chain worst, then the startup, then the long bond',
      ],
      answer: 0,
      why: 'A higher discount rate bites in proportion to how far away the money is. Almost all of the startup value sits in distant years, the bond spreads its coupons across three decades, and the pharmacy chain is collecting most of its cash now.',
      traps: {
        1: 'You picked this if you assume a bond must be the most rate-sensitive thing in any list.',
        2: 'You picked this if you ranked by how risky each feels rather than by when the cash arrives.',
      },
      rule: 'Rank rate damage by how far out the cash flows sit, not by how risky the business feels.',
    },

    /* ---------------- reason ---------------- */
    {
      shell: 'S17',
      kind: 'open',
      stem: 'Would you rather own a branded soft-drink company or a generic drug maker? Pick one and tell me why.',
      tests: 'Whether you can separate a commodity from a differentiated product, and then commit to a side.',
      clarify: [
        'Am I buying both at the same price, or is one materially cheaper?',
        'Is the soft-drink business the brand owner, or the bottler that fills the cans?',
      ],
      skeleton: [
        'Name the one variable that decides it: does the buyer have any question other than price?',
        'Generic drugs: an identical product from four plants, so the answer is price alone.',
        'Soft drink: shoppers ask for it by name, and that shows up as margin and annual price rises.',
        'Test the claim with evidence rather than assertion: gross margin, and price increases that stuck.',
        'Commit to one, then name the condition that would flip you.',
      ],
      criteria: [
        'Said a generic drug is a commodity because the buyer only cares about price',
        'Named brand or intangible assets as the moat behind the soft drink pricing power',
        'Pointed at gross margin or a record of price increases as the evidence, not just the logic',
        'Picked one side outright and named one thing that would change your mind',
      ],
      model:
        'I would take the branded soft-drink company. The generic maker sells something chemically identical to what three other plants produce, so the pharmacy buying it has exactly one question, which is price. That is what a commodity is, and returns in a commodity get competed down to the cost of capital. The soft drink is the opposite. Shoppers ask for it by name, which is why it can put four percent on the price every year and keep the volume, and you can see that in the gross margin and in a decade of increases that stuck. The moat is an intangible one: nobody is allowed to use the name. The weakness in my answer is that a brand is not permanent. If store-label colas keep getting better and shoppers stop caring about the label, the pricing power goes and I have paid a premium multiple for a generic maker with nicer packaging. So I would want to see volume growing too, not price alone.',
      follows: [
        'What would you pay for each, and does the price change your answer?',
        'How would you test whether the brand pricing power is still working?',
        'What if the generic maker were the lowest-cost producer in the industry?',
      ],
      flags: [
        'Saying the brand is better without pointing at a single number that shows it.',
        'Refusing to pick, and listing strengths of both instead.',
        'Treating any famous name as a moat without asking what price it can actually hold.',
      ],
      rule: 'If the buyer only asks about price, you are looking at a commodity, whatever the industry.',
    },
    {
      shell: 'S18',
      kind: 'open',
      stem: 'A medical device distributor has been profitable every quarter for three years, and its bank has just refused to extend more credit. Talk me through how that happens.',
      tests: 'Whether you can trace one dollar from the income statement toward the bank and say exactly where it stopped.',
      clarify: [
        'Is it growing, and roughly how fast?',
        'How long do the hospitals take to pay, and how long does it hold stock?',
      ],
      skeleton: [
        'Name the root cause first: profit is measured on accruals and cash is not.',
        'Working capital: stock bought and paid for up front, hospitals paying ninety days later.',
        'Show why growth widens the gap instead of closing it.',
        'Add the other causes: capex above depreciation, and debt principal that never hits the income statement.',
        'Say which line you would check first and what would confirm it.',
      ],
      criteria: [
        'Said revenue is booked when it is earned rather than when the cash arrives',
        'Named receivables or inventory growing faster than sales as the main drain',
        'Said that faster growth makes the cash gap wider, not narrower',
        'Named a second cause beyond working capital, such as capex or debt repayment',
      ],
      model:
        'Profit and cash run on different clocks. The distributor books the sale the day it ships a device, but the hospital pays ninety days later, and it had to buy and pay for that device before it shipped. So every extra sale ties cash up before it releases any. Growth makes this worse rather than better: the faster sales climb, the more stock and unpaid invoices it is carrying at any moment, so profit rises on paper while the bank balance drains. On top of that, if it is buying warehouses or vans, the money leaves at once while the income statement takes only a slice each year as depreciation. And debt repayments never appear on the income statement at all, only the interest does. The first thing I would do is put cash from operations next to net income for three years. If the gap is persistent and widening, the profit is real accounting but it is not becoming money, and the bank has looked at the same page.',
      follows: [
        'Which of those causes would worry you most as the owner?',
        'What would you change first if you ran the company?',
        'Could the profit itself be wrong, rather than just uncollected?',
      ],
      flags: [
        'Saying receivables and stopping, with no mechanism attached to it.',
        'Blaming the bank instead of explaining the accounting.',
        'Never saying that growth is the thing making the drain bigger.',
      ],
      rule: 'A profitable company runs out of cash when the profit is sitting in stock and unpaid invoices.',
    },
    {
      shell: 'S19',
      kind: 'open',
      stem: 'The dentist on your street is retiring and offers to sell you the practice. There are no comparable public companies. How do you put a number on it?',
      tests: 'Whether your valuation instincts survive a business with no analysts and no comparables.',
      clarify: [
        'Am I buying the practice only, or the building it sits in as well?',
        'Does the retiring dentist do most of the treatment himself?',
      ],
      skeleton: [
        'Say what you are buying: cash flows, a patient list, a lease, and equipment.',
        'Normalise the earnings: add back the owner pay and personal costs, subtract a market wage for a replacement.',
        'Apply a low multiple and justify the level, not just the method.',
        'Cross-check against what it would cost to fit out a new practice nearby.',
        'Test the fragility: lease length, and how many patients follow the dentist out.',
      ],
      criteria: [
        'Said you would normalise earnings by replacing the owner pay with a market wage',
        'Named a low multiple and gave a reason tied to fragility or illiquidity',
        'Used a second method as a cross-check, such as replacement cost',
        'Named the risk that patients are loyal to the dentist rather than the practice',
      ],
      model:
        'I would value the cash flow first and then check it two other ways. Start by normalising: take the reported profit, add back what the dentist pays himself and anything personal running through the books, then subtract what it would cost to hire a dentist to do that work. I am buying a business, not a job, and that adjustment is usually the largest single number in the exercise. Then I would apply a low multiple, low single digits, because the cash flows are small, fragile and hard to sell on to anyone else. As a cross-check I would ask what it costs to fit out a new surgery two streets away, since that caps what a rational buyer pays. Lease length matters too, because a short lease in a good spot means the landlord captures the value rather than me. The weakness in my answer is that I cannot easily test the biggest risk, which is how many patients are loyal to the practice and how many are loyal to the man leaving.',
      follows: [
        'Which of your methods do you trust most, and why?',
        'What single number would you most want before paying?',
        'How does your answer change if a corporate chain opens two doors down?',
      ],
      flags: [
        'Going straight to a discounted cash flow without normalising the owner pay.',
        'Quoting a multiple with no reason for why it is that number.',
        'Giving one method and never cross-checking it against anything.',
      ],
      rule: 'With no comparables, normalise the earnings first and then triangulate with a second method.',
    },
    {
      shell: 'S20',
      kind: 'open',
      stem: 'A razor company posts its highest quarterly revenue on record and the stock falls 12% the same morning. What happened?',
      tests: 'Whether you understand that prices move against expectations rather than against facts.',
      clarify: [
        'Did they give guidance for the next quarter alongside the result?',
        'Did the whole sector move that morning, or only this stock?',
      ],
      skeleton: [
        'Lead with the frame: a share price trades on the gap between results and expectations.',
        'First candidate: revenue beat while margin or earnings missed below it.',
        'Second: guidance for the coming period was cut.',
        'Third: the quality of the revenue, discounting, a bulk order, or ballooning receivables.',
        'Fourth: nothing to do with the company, a rate move or a sector de-rating.',
        'Rank them, and say what you would check first.',
      ],
      criteria: [
        'Said explicitly that prices respond to surprises against expectations, not to facts',
        'Named a margin or earnings miss below the revenue line as a candidate',
        'Named guidance for the coming period as a separate candidate',
        'Questioned the quality of the revenue, such as discounting or a one-off order',
      ],
      model:
        'Record revenue is a fact, and prices move on surprises rather than facts, so something the market cared about must have come in below what it already expected. My lead candidate is that the revenue was bought: if they discounted to shift cartridges, gross margin falls and earnings can miss even while the top line sets a record. Second is guidance, because the market prices the next four quarters and not the last one, so a cut to the outlook overrides a good print. Third is the quality of the revenue itself, a one-time bulk order or a retail channel stuffed with stock, which you would see as receivables and inventory growing faster than sales. Fourth, it may not be about the company at all, since a rate move can compress the multiple straight through good results. The weakness in leading with margin is that 12% is a large fall for a margin miss alone, so guidance is probably doing some of the work. I would want the margin line and the outlook before committing.',
      follows: [
        'Which of those would worry you most as an owner?',
        'How would you check the channel-stuffing story in the filings?',
        'What would make you buy the shares after the fall?',
      ],
      flags: [
        'Answering that the market is irrational, which ends the conversation.',
        'Listing every possible cause with no ranking and no first check.',
        'Treating record revenue as automatically good news for a shareholder.',
      ],
      rule: 'A stock moves against expectations, so ask what was expected before you explain the result.',
    },
  ],
}
