import type { PracticeTest } from './types'

export const TEST_1: PracticeTest = {
  id: 't1',
  n: 1,
  title: 'Opening Round',
  blurb:
    'A baseline sitting: answer each one as you would in the room, then read the feedback before looking anything up.',
  items: [
    /* ---------------- recall ---------------- */
    {
      shell: 'S01',
      kind: 'mc',
      stem: 'You want to know what a grocery chain owns and what it owes today. Which statement answers that, and what stretch of time does it cover?',
      choices: [
        'The income statement, over the past year',
        'The balance sheet, as of one day',
        'The cash flow statement, over the year',
      ],
      answer: 1,
      why: 'Only the balance sheet lists holdings and obligations, and it fixes them at a single moment. Take it again tomorrow and every figure can be different.',
      traps: {
        0: 'You picked this if you think profitability tells you what is owned. It reports a period of performance, not a position.',
        2: 'You picked this if you read cash in the bank as everything the business owns. Cash is one line among several.',
      },
      rule: 'Match the question to the statement: a position on one day, or performance across a period.',
    },
    {
      shell: 'S02',
      kind: 'mc',
      stem: 'A bakery agrees a $600 order with a cafe in February, delivers the bread in March, and is paid in April. In which month does the bakery record the $600 of revenue?',
      choices: [
        'February, when the customer committed to the order',
        'March, when the bread was actually delivered',
        'April, when the cash reached the bank',
      ],
      answer: 1,
      why: 'Revenue is earned when you hand over what you promised, so March is the month that counts. The order is a promise and the payment is a separate cash event.',
      traps: {
        0: 'You picked this if you book revenue when a customer signs. Nothing has been earned until you deliver.',
        2: 'You picked this if you book revenue when the money lands. That is cash accounting, not accrual accounting.',
      },
      rule: 'Book revenue in the period you deliver, and let the cash arrive on its own schedule.',
    },
    {
      shell: 'S03',
      kind: 'mc',
      stem: "A clothing retailer's rent, head office salaries and marketing all rose sharply this year, while the prices it pays suppliers held flat. Which margin captures that change without also reflecting how the retailer is financed?",
      choices: [
        'Gross margin, after the direct cost of goods',
        'Operating margin, after the cost of running it',
        'Net margin, after interest and tax as well',
      ],
      answer: 1,
      why: 'Rent, salaries and marketing sit below gross profit, so they move operating margin while gross margin holds steady. Gross margin judges the product; operating margin judges the business around it.',
      traps: {
        0: 'You picked this if you think every cost hits gross margin. Only the direct cost of the goods does.',
        2: 'You picked this if you read net margin as the operating picture. It also reflects debt and the tax rate.',
      },
      rule: 'Judge the product on gross margin, the business on operating margin, and the financing on net margin.',
    },
    {
      shell: 'S04',
      kind: 'mc',
      stem: 'A grocery chain buys for 1,900 stores at once and runs the densest delivery network in its region. It can undercut local rivals on price and still earn more per store. Which moat is that?',
      choices: [
        'A cost advantage built on scale and density',
        'A network effect, since each store helps others',
        'A switching cost, since shoppers return from habit',
      ],
      answer: 0,
      why: 'Buying and delivering more cheaply than anyone else is a structurally lower cost to serve. Scale advantages of this kind compound as the chain grows, rather than expiring like a lucky contract.',
      traps: {
        1: 'You picked this if you call any scale effect a network effect. Shoppers here do not make the stores more useful to each other.',
        2: 'You picked this if you count habit as a switching cost. A shopper loses nothing by crossing the street.',
      },
      rule: 'Name the moat by what stops a rival copying you, not by what customers happen to do.',
    },
    {
      shell: 'S05',
      kind: 'mc',
      stem: 'A car wash chain earns 6% on the capital it puts into each new site, and that capital costs it 9%. Management now wants to double the pace of openings. What does the faster growth do to value?',
      choices: [
        'Growth creates value, since more sites lift the total profit',
        'Growth stays neutral to value until the returns turn negative',
        'Growth destroys value faster, since each site earns below cost',
      ],
      answer: 2,
      why: 'Every new site turns nine cents of capital cost into six cents of return, so each one subtracts value. Growth multiplies whatever gap already exists between the return and the hurdle.',
      traps: {
        0: 'You picked this if you read more profit as more value. Profit earned below the cost of capital still leaves owners worse off.',
        1: 'You picked this if you think value is destroyed only when returns go negative. The hurdle is the cost of capital, not zero.',
      },
      rule: 'Growth only creates value when the return on capital beats the cost of that capital.',
    },
    {
      shell: 'S06',
      kind: 'mc',
      stem: 'You are buying a restaurant group outright, and it is sitting on a large pile of cash. How does that cash affect the enterprise value you are paying for the operating business, and why?',
      choices: [
        'It raises the price, since you acquire that cash too',
        'It leaves the price unchanged, since cash is not operations',
        'It lowers the price, since you receive that cash immediately',
      ],
      answer: 2,
      why: 'Enterprise value prices the operating business alone. Because you own the cash from the day you buy, it works as a rebate on what you effectively paid for the restaurants.',
      traps: {
        0: 'You picked this if you are adding cash to enterprise value. The bridge adds debt and subtracts cash.',
        1: 'You picked this if you think excluding cash from operations means ignoring it. It still changes your effective price.',
      },
      rule: 'Enterprise value prices the operating business, so debt goes on and the cash you inherit comes off.',
    },
    {
      shell: 'S07',
      kind: 'mc',
      stem: 'A grocery chain sells steadily through recessions, yet its shares have moved about 1.4% for every 1% move in the market. What does that beta of 1.4 measure?',
      choices: [
        'How far the shares move with the market',
        'How risky the grocery business itself is',
        'How much return the shares earned above expectations',
      ],
      answer: 0,
      why: 'Beta reads past share prices against the index, not the trading of the business underneath. Steady sales can sit under shares that still swing, which is the standard complaint about CAPM.',
      traps: {
        1: 'You picked this if you read beta as business risk. It measures co-movement of the shares, not the durability of the sales.',
        2: 'You picked this if you are describing alpha, which is return beyond what the risk taken should have produced.',
      },
      rule: 'Beta measures co-movement with the market, and only the risk you cannot diversify away gets paid for.',
    },
    {
      shell: 'S08',
      kind: 'mc',
      stem: 'A coffee roaster pays a $4 premium for the right to buy a bag of beans at $90 any time in the next three months. Beans are at $70 when the contract expires. What happens?',
      choices: [
        'The roaster must buy at $90 and loses $20',
        'The roaster owes the seller the $20 price difference',
        'The right lapses and the loss stops at $4',
      ],
      answer: 2,
      why: 'A call is a right and not an obligation, so you walk away whenever the strike is worse than the market. That is what caps the buyer loss at the premium already paid.',
      traps: {
        0: 'You picked this if you are treating a call like a forward. A forward obliges you to buy; an option does not.',
        1: 'You picked this if you are settling it like a forward, where whoever is on the wrong side of the price pays the difference. An option pays from seller to buyer or not at all.',
      },
      rule: 'The option buyer holds a right and a capped loss; the seller collects a premium and holds the obligation.',
    },

    /* ---------------- apply ---------------- */
    {
      shell: 'S09',
      kind: 'num',
      stem: 'A gym chain records $12M more depreciation this year on its equipment. The tax rate is 25% and nothing else changes. By how much does cash at the bottom of the cash flow statement move?',
      answer: 3,
      unit: '$M',
      format: 'Answer as a positive number if cash rises, e.g. 4',
      work: [
        { label: 'Operating profit falls by the charge', value: '($12M)' },
        { label: 'Tax saved at 25%', value: '+$3M', running: 'Net income ($9M)' },
        { label: 'Add the charge back, no cash left', value: '+$12M', running: 'Cash from operations +$3M' },
        { label: 'Nothing else moves', value: '$0', running: 'Cash +$3M' },
      ],
      why: 'Cash rises while profit falls, because the charge itself never left the bank and the tax it saved you is real money. The gym is genuinely more worn out, so the bill simply arrives later.',
      rule: 'Add back any charge that never left the bank, and keep the tax that charge saved you.',
    },
    {
      shell: 'S10',
      kind: 'num',
      stem: 'A clothing retailer earns $50M of net income. Depreciation was $10M. Over the year receivables rose $9M, inventory rose $7M, and payables rose $3M. What is cash from operations?',
      answer: 47,
      unit: '$M',
      format: 'Answer as a number, e.g. 52',
      work: [
        { label: 'Net income', value: '+$50M', running: '$50M' },
        { label: 'Add back depreciation, no cash left', value: '+$10M', running: '$60M' },
        { label: 'Receivables rose, sales not yet collected', value: '($9M)', running: '$51M' },
        { label: 'Inventory rose, cash sitting on shelves', value: '($7M)', running: '$44M' },
        { label: 'Payables rose, suppliers not yet paid', value: '+$3M', running: '$47M' },
      ],
      why: 'Working capital is the gap between profit and cash. Money customers owe you and stock you have not sold are profit you have booked but cannot spend yet.',
      rule: 'An operating asset that grows consumes cash; a bill you have not yet paid keeps it.',
    },
    {
      shell: 'S11',
      kind: 'num',
      stem: 'A restaurant group has 40M shares trading at $15. It carries $250M of debt and holds $50M of cash. EBITDA is $100M. What EV/EBITDA multiple is it trading at?',
      answer: 8,
      unit: 'x',
      format: 'Answer as a number, e.g. 11',
      work: [
        { label: 'Equity value: 40M shares at $15', value: '+$600M', running: '$600M' },
        { label: 'Add debt', value: '+$250M', running: '$850M' },
        { label: 'Subtract cash', value: '($50M)', running: 'EV $800M' },
        { label: '$800M divided by $100M', value: '8x', running: '8x' },
      ],
      why: 'The multiple prices the whole operating business against the profit that business produces. Both halves of the ratio therefore have to ignore how the restaurants were financed.',
      rule: 'Build enterprise value first, then divide by a profit line that sits above interest.',
    },
    {
      shell: 'S12',
      kind: 'num',
      stem: 'A car wash charges $20 a wash. Water, soap and the labour for that wash cost $8. Rent and salaries come to $54,000 a year. How many washes does it take to break even?',
      answer: 4500,
      format: 'Answer as a number of washes, e.g. 3200',
      work: [
        { label: 'Price per wash', value: '+$20' },
        { label: 'Variable cost per wash', value: '($8)', running: 'Contribution $12' },
        { label: 'Fixed costs to cover', value: '($54,000)' },
        { label: '$54,000 divided by $12', value: '4,500 washes', running: 'Breakeven 4,500' },
      ],
      why: 'Breakeven counts how many units it takes for contribution to cover the fixed base. Past that point the fixed costs are already paid, so most of each extra $12 drops through to profit.',
      rule: 'Break even on contribution per unit, not on price, and every unit past it is mostly profit.',
    },
    {
      shell: 'S13',
      kind: 'num',
      stem: "A bakery's sales are growing 9% a year while inflation runs at 3%. Using the rule of 72, roughly how many years until the bakery is selling twice as much bread?",
      answer: 12,
      tol: 0.5,
      unit: ' years',
      format: 'Answer as a number, e.g. 9',
      work: [
        { label: 'Nominal sales growth', value: '+9%' },
        { label: 'Inflation taken out', value: '(3%)', running: 'Real growth +6%' },
        { label: '72 divided by 6', value: '+12', running: 'About 12 years' },
      ],
      why: 'Twice the money is not twice the bread. Part of the 9% is just higher prices, so strip inflation out before you compound or you will credit the bakery with growth it never had.',
      rule: 'Take inflation off a growth rate before you compound it, then divide 72 by what is left.',
    },
    {
      shell: 'S14',
      kind: 'mc',
      stem: 'A clothing retailer earns $40M of net income this year. It pays no dividend, issues no shares, and buys nothing back. Which balance sheet line has to rise by $40M?',
      choices: [
        'Cash in the bank, by the same amount',
        'Retained earnings, the profit kept in the business',
        "The owner's original money put into the business",
      ],
      answer: 1,
      why: 'Profit the business keeps lands in retained earnings, which is how the two sides still balance after a profitable year. Whether cash also rose depends on what happened to working capital.',
      traps: {
        0: 'You picked this if you are treating net income as cash. Profit is booked when earned, and the cash may still be in receivables.',
        2: "You picked this if you are mixing the owner's contributed money with profit the company earned. Those are two separate lines.",
      },
      rule: 'Profit you keep flows into retained earnings; whether it also shows up as cash is a separate question.',
    },
    {
      shell: 'S15',
      kind: 'mc',
      stem: 'You are comparing two grocery chains. Both spend heavily every year on stores and refrigeration, and one carries far more debt than the other. Which multiple compares their operations most fairly?',
      choices: [
        'EV/EBITDA, since it removes accounting policy from view',
        'EV/EBIT, since it charges them for consuming assets',
        'P/E, since it captures what shareholders actually earn',
      ],
      answer: 1,
      why: 'Using enterprise value neutralises the different debt loads, and keeping depreciation in charges each chain for wearing out its stores. That matters when the spending is heavy and genuinely recurring.',
      traps: {
        0: 'You picked this if you treat EBITDA as neutral here. It writes out the capital spending these chains cannot avoid.',
        2: 'You picked this if you compared on P/E. It sits below interest, so the different debt loads distort the comparison.',
      },
      rule: 'Use an enterprise value multiple to strip out leverage, and keep depreciation in when the assets really wear out.',
    },
    {
      shell: 'S16',
      kind: 'mc',
      stem: 'Long-term rates rise by one percentage point. Three businesses: a profitable grocery chain, a steady coffee roaster, and a loss-making clothing brand whose plan shows first profits in year eight. Which is hurt most?',
      choices: [
        'The grocery chain, whose thin margins cannot absorb costs',
        'The coffee roaster, whose borrowing costs reset the soonest',
        'The clothing brand, whose value sits in distant years',
      ],
      answer: 2,
      why: 'A higher discount rate reduces cash flows in proportion to how far away they are. Profit promised in year eight loses far more present value than profit arriving this year.',
      traps: {
        0: 'You picked this if you ranked by margin. A higher discount rate attacks the timing of the cash, not the thinness of it.',
        1: 'You picked this if you ranked by borrowing cost. Real as that is, the duration of the cash flows dominates the re-rating.',
      },
      rule: 'When rates rise, the asset whose cash arrives furthest in the future falls hardest.',
    },

    /* ---------------- reason ---------------- */
    {
      shell: 'S17',
      kind: 'open',
      stem: 'Would you rather own a chain of neighbourhood gyms or a chain of car washes? Pick one and tell me why.',
      tests: 'Whether you compare the two on the same handful of drivers and then commit, instead of describing each in turn.',
      clarify: [
        'Do I own the property, or lease the sites and run the operation?',
        'Are the gyms on monthly memberships, and do the washes sell a monthly pass?',
      ],
      skeleton: [
        'Say which one you are taking before you justify it.',
        'Set the four things you will compare: revenue quality, working capital, fixed costs, and ease of entry.',
        'Run the gym through all four drivers before you touch the car wash.',
        'Run the car wash through the same four, in the same order.',
        'Both have weak moats, so decide on cash timing and location.',
        'Land on one and name the condition that would flip you.',
      ],
      criteria: [
        'Said gym dues are collected in advance, so members fund the working capital',
        'Said a large share of gym members pay every month and rarely turn up',
        'Named the fixed cost base and said profit swings hard either side of breakeven',
        'Committed to one and named a condition that would change your answer',
      ],
      model:
        'I would take the gyms, mainly because of when the cash arrives. Members pay their dues at the start of the month before they use anything, so customers fund the business rather than the other way round. On top of that, a large share of them pay every month and rarely come, so one floor can carry far more members than it could physically serve. A car wash is paid per visit, so there is no float, and demand moves with the weather. Both cost bases are almost entirely fixed, rent and equipment and a staffed site, so profit swings hard either side of breakeven, and the gym clears breakeven on recurring dues rather than on a run of dry Saturdays. The weakness in my answer is the moat. Neither has one: anyone can open across the street, switching costs are close to zero, and my membership base is exactly what a new entrant would take. If the gyms sat on short leases in a crowded catchment, I would flip to the washes.',
      follows: [
        'What happens to each of them in a recession?',
        'Would you rather own the gym brand or the buildings?',
        'What single number would you check before buying?',
      ],
      flags: [
        'Listing features of each business and never choosing one.',
        'Missing that gym dues are collected before the service is delivered.',
        'Treating the weather risk as an afterthought instead of a revenue driver.',
      ],
      rule: 'Compare two businesses on the same few drivers, then commit to one and say what would change your mind.',
    },
    {
      shell: 'S18',
      kind: 'open',
      stem: 'A bakery chain has reported a profit every quarter for two years and is about to miss payroll. How is that possible?',
      tests: 'Whether accrual accounting is intuition for you, or a definition you can only recite.',
      clarify: [
        'Is it growing, and how fast?',
        'Has it been opening new sites, or holding the footprint steady?',
      ],
      skeleton: [
        'Name the root cause first: profit is an accrual measure and cash is not.',
        'Working capital: cafes pay in ninety days while flour and wages leave weekly.',
        'Capital spending: ovens and fit-outs leave the bank faster than depreciation charges them.',
        'Debt: repaying principal never touches the income statement at all.',
        'Say which one you would check first, and where you would look.',
      ],
      criteria: [
        'Said profit is booked when earned while cash moves on its own schedule',
        'Named receivables or inventory growing faster than sales',
        'Named capital spending running above the depreciation charge',
        'Said you would compare cash from operations with net income across several years',
      ],
      model:
        'Profit is measured on accruals and cash is not, so the two can pull apart for years. The version I would bet on here is working capital in a growing business. If the bakery has been winning wholesale accounts, it books the sale when the bread is delivered, but the cafe pays in ninety days, while flour, rent and wages leave the bank every week. So every extra order adds profit and consumes cash at the same time. Second is capital spending: a new site and its ovens are paid for in full up front, while the income statement is charged only a slice each year as depreciation. Third is debt, where principal repayments never appear on the income statement at all. I would go straight to the cash flow statement and compare cash from operations with net income over three years. The weakness in my answer is that I am assuming growth. If sales are flat, working capital is not the culprit and I would look at the capex line first.',
      follows: [
        'Which of those would worry you most as an owner?',
        'How would you fix it if you ran the bakery?',
        'What if sales were flat rather than growing?',
      ],
      flags: [
        'Saying "receivables" and stopping there.',
        'Reaching for fraud before checking the ordinary explanations.',
      ],
      rule: 'When profit and cash disagree, check working capital, capital spending and debt repayment before anything else.',
    },
    {
      shell: 'S19',
      kind: 'open',
      stem: 'The independent coffee roaster on your street is for sale. No analysts cover it and there is no public company like it. How would you value it?',
      tests: 'Whether valuation ideas survive contact with a business that has no data, and whether you normalise before you multiply.',
      clarify: [
        'Am I buying the business only, or the building as well?',
        'Does the owner work there full time, and is she staying on?',
      ],
      skeleton: [
        'Say what you are actually buying: cash flows, a lease, equipment, a location.',
        'Normalise the earnings: strip out owner pay and personal costs, then subtract a market wage.',
        'Put a multiple on that number and justify the level you chose.',
        'Cross-check against what it would cost to open the same roaster across the street.',
        'Test the fragility: lease length, one large wholesale account, the owner relationships.',
      ],
      criteria: [
        'Said you would normalise earnings for owner compensation before valuing anything',
        'Named a specific cross-check, such as replacement cost or recent local sales',
        'Gave a reason the multiple should be low, such as fragility or illiquidity',
        'Named a specific risk, such as the lease term or customer concentration',
      ],
      model:
        'I would value the cash flow and then check it two other ways. First, normalise: take the profit, add back whatever the owner pays herself and any personal costs run through the business, then subtract a market wage for whoever actually has to run it, because I am buying a business and not a job. Then I would put a low single-digit multiple on that number, low because the cash flows are small, fragile and hard to sell on, and because a chain could open on the same block. As a cross-check I would ask what it would cost to build the same roaster from scratch, since that caps what a rational buyer should pay, and what similar shops nearby changed hands for. Then the risk work: how long the lease runs, how much of the wholesale revenue sits with one or two cafes, and how much of the goodwill walks out with the current owner. The weak point is the multiple. I am choosing it from judgement, so I would want two real local sale prices before committing.',
      follows: [
        'Which of your three methods do you trust most?',
        'What is the single biggest risk in your number?',
        'What would you pay if the lease had one year left?',
      ],
      flags: [
        'Reaching for a discounted cash flow before normalising owner pay.',
        'Quoting a multiple with no reason for the level you chose.',
        'Valuing the profit without asking who runs the shop afterwards.',
      ],
      rule: 'With no comparables, normalise the earnings first, then price them and cross-check the answer another way.',
    },
    {
      shell: 'S20',
      kind: 'open',
      stem: 'A grocery chain reports its highest quarterly sales ever and the stock falls 9% that morning. Talk me through what happened.',
      tests: 'Whether you know that prices move against expectations rather than against facts.',
      clarify: [
        'Did they give guidance for the coming year alongside the result?',
        'Did the rest of the sector move that morning too?',
      ],
      skeleton: [
        'Lead with the frame: prices respond to surprises, not to facts.',
        'Expectations: sales beat while margin or profit missed.',
        'Guidance: the outlook for the coming year was cut.',
        'Quality: the sales were bought with discounting, or stock and receivables ballooned.',
        'Outside the company: rates or a sector move re-rated the multiple.',
        'Say which one you would check first.',
      ],
      criteria: [
        'Said the price moves against expectations, not against the raw result',
        'Named margin or profit missing while sales beat',
        'Named guidance about future periods as a separate possible cause',
        'Named a cause outside the company, such as rates or a sector move',
      ],
      model:
        'Record sales is a fact, and prices move on surprises. My first guess is that sales beat while something below the top line missed. A grocer can buy volume with promotions, so the aisles get busier while gross margin falls and profit lands short of what the market expected. The second candidate is guidance: the market prices next year rather than last quarter, so if management flagged softer demand or rising wage costs, a good print can still be sold. Third is the quality of the sales, a one-off week of stocking up, or inventory and receivables growing faster than sales, which says the growth may not convert into cash. And it might have nothing to do with the company at all: if rates moved or the whole sector de-rated that morning, the multiple fell rather than the business. I would ask for the gross margin line and the guidance first. The weakness is that without knowing how the sector traded, I cannot rule that last explanation out.',
      follows: [
        'If you could see one number tomorrow morning, which would it be?',
        'How would you check the discounting story?',
        'What would make you buy it after the fall?',
      ],
      flags: [
        'Saying the market is irrational, which ends the conversation.',
        'Explaining only the business and never mentioning expectations.',
      ],
      rule: 'A stock moves on the gap between the result and what was expected, so separate the business from the sentiment.',
    },
  ],
}
