import type { PracticeTest } from './types'

export const TEST_5: PracticeTest = {
  id: 't5',
  n: 5,
  title: 'The Long Haul',
  blurb: 'Twenty questions phrased the way an interviewer would actually ask them: less scaffolding, the same reasoning underneath.',
  items: [
    /* ---------------- recall ---------------- */
    {
      shell: 'S01',
      kind: 'mc',
      stem: "A hotel group tells you its borrowings came down steadily through the year. You want to know exactly what it owed on 31 December. Which statement answers that, and over what window?",
      choices: [
        'The income statement, across the whole year',
        'The balance sheet, on a single day',
        'The cash flow statement, over the year',
      ],
      answer: 1,
      why: 'Debt outstanding is a balance, and only the balance sheet reports balances. It is a photograph taken on one date, so take it again tomorrow and the figure can be different.',
      traps: {
        0: 'You picked this if you follow the phrase "through the year" to the income statement; it reports earning and spending, never what is owed.',
        2: 'You picked this if you expect the cash flow statement to list balances; it reports movements between two dates instead.',
      },
      rule: 'Ask whether you want a balance or a flow, and the statement picks itself.',
    },
    {
      shell: 'S02',
      kind: 'mc',
      stem: 'A data centre landlord houses a tenant through December and invoices $600,000 on 31 December. The tenant pays in February. When does the sale count, and what happens in February?',
      choices: [
        'A December sale, with February as cash collection',
        'A February sale, with December showing no revenue',
        'A December sale, with February adding more revenue',
      ],
      answer: 0,
      why: 'You earned the revenue by supplying the space in December, so December carries the sale. February moves money only: a receivable turns into bank balance, and nothing new is earned.',
      traps: {
        1: 'You picked this if you book revenue when the cash lands; accrual accounting books it when the service was delivered.',
        2: 'You picked this if you count the same service twice, once when earned and again when paid.',
      },
      rule: 'Book a sale when you deliver, and treat the payment that follows as a cash event.',
    },
    {
      shell: 'S03',
      kind: 'mc',
      stem: "You want to know whether a hotel group's rooms earn more per night than a rival's, before head office costs and financing enter the picture. Which margin do you read?",
      choices: [
        'Gross margin, which judges the product itself',
        'Operating margin, which judges the whole company',
        'Net margin, which judges the capital structure too',
      ],
      answer: 0,
      why: 'Gross margin is what the product earns after the direct cost of delivering it and before the cost of running the company. The other two blend in head office, interest and tax, none of which the room controls.',
      traps: {
        1: 'You picked this if you use operating margin for product questions; it has already absorbed head office and overhead.',
        2: 'You picked this if you judge operations on net margin; it moves with debt loads and tax rates.',
      },
      rule: 'Pick the margin that stops just above the costs the question told you to ignore.',
    },
    {
      shell: 'S04',
      kind: 'mc',
      stem: 'A single pipeline carries gas from one field to one city. Volumes support one line, and building another would leave both owners earning below their cost of capital. Which moat is this?',
      choices: [
        'Efficient scale, since the market pays for one',
        'Network effects, since each new user adds value',
        'Switching costs, since the customer has nowhere else',
      ],
      answer: 0,
      why: 'The barrier here is arithmetic rather than contract: the market is too small to fund two lines, so nobody rational builds one. The same smallness that keeps rivals out also caps how much you can ever grow.',
      traps: {
        1: 'You picked this if you call any physical network a network effect; that moat needs users making the product better for one another.',
        2: 'You picked this if you read a captive customer as a switching cost; a switching cost is what the customer pays to leave, and here there is nowhere to go.',
      },
      rule: 'When a market only pays for one player, the barrier is the size of the market.',
    },
    {
      shell: 'S05',
      kind: 'mc',
      stem: 'A wind farm operator earns 6% on invested capital while that capital costs 9%. Management plans to double the capital it deploys next year. What happens to value?',
      choices: [
        'Value falls, because each new dollar earns below cost',
        'Value holds, because growth and cost offset each other',
        'Value rises, because a bigger asset base earns more',
      ],
      answer: 0,
      why: 'Growth only creates value when the return on new capital clears the cost of that capital. At 6% against 9%, every extra dollar deployed loses three cents a year, so doubling the base doubles the damage.',
      traps: {
        1: 'You picked this if you treat the gap between return and cost as something that nets out; it repeats on every dollar you add.',
        2: 'You picked this if you read growth as value by itself; a bigger base of below-hurdle assets is a bigger problem.',
      },
      rule: 'Growth creates value only above the hurdle rate; below it, growth burns money faster.',
    },
    {
      shell: 'S06',
      kind: 'mc',
      stem: 'You are buying a toll road company outright. It holds $200 million of cash it does not need in order to operate. How does that cash affect what the operating business costs you?',
      choices: [
        'It lowers the price, because you receive it',
        'It leaves the price unchanged, because operations continue',
        'It raises the price, because it is an asset',
      ],
      answer: 0,
      why: 'Enterprise value is what the operating business costs free of its financing. The day you own the company you own its bank account, so that cash comes straight back and rebates part of what you paid.',
      traps: {
        1: 'You picked this if you decide cash is irrelevant because it does not run the road; excess cash still reduces the effective price.',
        2: 'You picked this if you add cash to enterprise value; you are already receiving it, so adding it charges yourself twice.',
      },
      rule: 'Subtract the cash you get back, and only the cash the business does not need to run.',
    },
    {
      shell: 'S07',
      kind: 'mc',
      stem: 'A regulated water utility has steady earnings, yet its shares have moved about 1.2% for every 1% move in the index. What does that 1.2 tell you?',
      choices: [
        'How much it co-moves with the market',
        'How likely the business is to lose money',
        'How much debt sits in the capital structure',
      ],
      answer: 0,
      why: 'Beta is measured from past price movement against the index, and CAPM pays you only for that undiversifiable part. A steady business can carry a high beta, which is the standard complaint about using beta as risk.',
      traps: {
        1: 'You picked this if you read beta as business risk; it captures co-movement, not the chance of permanent loss.',
        2: 'You picked this if you expect beta to report leverage; it is read off share prices, not off the balance sheet.',
      },
      rule: 'Beta measures co-movement with the market, not the chance of losing your money.',
    },
    {
      shell: 'S08',
      kind: 'mc',
      stem: 'A data centre landlord sells a call option on shares it already owns and collects the premium. What has it taken on?',
      choices: [
        'An obligation to sell if the buyer exercises',
        'An obligation to buy the shares at expiry',
        'A right to sell whenever the price suits',
      ],
      answer: 0,
      why: 'The premium buys a choice, and the seller is the one who gave that choice up. Because it already owns the shares, its upside is now capped at the strike plus the premium, and the decision to trade belongs to someone else.',
      traps: {
        1: 'You picked this if you swap the two sides of a call; the buyer is the one who may buy, so the seller is the one who may have to deliver.',
        2: 'You picked this if you think collecting a premium buys a right; the money flows to whoever gives up the choice.',
      },
      rule: 'Whoever pays the premium holds the choice; whoever collects it holds the obligation.',
    },

    /* ---------------- apply ---------------- */
    {
      shell: 'S09',
      kind: 'num',
      stem: "A wind farm operator's depreciation rises by $32 million. The tax rate is 25% and nothing else changes. By how much does cash at the end of the year change?",
      answer: 8,
      unit: '$M',
      format: 'Answer as a number in $M, e.g. 15',
      work: [
        { label: 'Depreciation charged against operating profit', value: '($32M)' },
        { label: 'Tax saved at 25%', value: '+$8M', running: 'net income ($24M)' },
        { label: 'Add back the charge, no money moved', value: '+$32M', running: 'cash +$8M' },
        { label: 'Assets: cash +$8M, plant ($32M)', value: '($24M)', running: 'equity also ($24M), it balances' },
      ],
      why: 'The charge itself moves no money, but the tax bill it removes is cash you never have to send. That is why profit falls and cash rises in the same year.',
      rule: 'A non-cash charge leaves you with more cash, because the tax it saves is real.',
    },
    {
      shell: 'S10',
      kind: 'num',
      stem: 'A regional airport reports net income of $60 million and depreciation of $25 million. Receivables rose $15 million and payables rose $10 million. What is cash from operations?',
      answer: 80,
      unit: '$M',
      format: 'Answer as a number in $M, e.g. 45',
      work: [
        { label: 'Net income', value: '+$60M', running: '$60M' },
        { label: 'Add back depreciation, no money moved', value: '+$25M', running: '$85M' },
        { label: 'Receivables up, billed but not banked', value: '($15M)', running: '$70M' },
        { label: 'Payables up, incurred but not yet paid', value: '+$10M', running: '$80M' },
      ],
      why: 'Profit is counted when you earn and use things up; cash is counted when the bank moves. Working capital is the timing gap between the two, and it can run either way.',
      rule: 'An asset rising uses up cash; a liability rising leaves cash in the account.',
    },
    {
      shell: 'S11',
      kind: 'num',
      stem: 'A data centre landlord has a market cap of $700 million, debt of $500 million, and cash of $100 million. EBITDA is $100 million. What EV/EBITDA multiple does it trade at?',
      answer: 11,
      unit: 'x',
      format: 'Answer as a number, e.g. 7',
      work: [
        { label: 'Market cap, what shareholders own', value: '+$700M', running: '$700M' },
        { label: 'Add debt, a claim on the same assets', value: '+$500M', running: '$1,200M' },
        { label: 'Subtract cash you receive on purchase', value: '($100M)', running: 'EV $1,100M' },
        { label: 'Divide by EBITDA', value: '/ $100M', running: '11x' },
      ],
      why: 'The bridge turns what shareholders own into what the whole business costs, so the multiple compares like with like. EBITDA sits above interest, so pairing it with equity value alone would flatter a heavy borrower.',
      rule: 'Match an enterprise-value numerator to a profit measured before interest, never to net income.',
    },
    {
      shell: 'S12',
      kind: 'num',
      stem: 'A hotel charges $200 a night. Cleaning, laundry and breakfast cost $60 a night. Fixed costs run $2,800,000 a year. How many room nights does it need to break even?',
      answer: 20000,
      format: 'Answer as a number of room nights, e.g. 15000',
      work: [
        { label: 'Price per room night', value: '+$200' },
        { label: 'Variable cost per room night', value: '($60)', running: 'contribution $140' },
        { label: 'Fixed costs to cover each year', value: '($2,800,000)' },
        { label: 'Divide $2,800,000 by $140', value: '20,000 nights', running: 'breakeven 20,000' },
      ],
      why: 'Each night sold puts $140 toward the fixed costs and nothing toward profit until they are covered. Past that point almost the whole $140 falls to profit, which is why occupancy swings a hotel so violently.',
      rule: 'Divide the fixed costs by the contribution per unit to find how many you must sell.',
    },
    {
      shell: 'S13',
      kind: 'num',
      stem: 'A toll road raises its toll 6% a year and inflation runs 2% a year. Using the rule of 72, roughly how long until the toll doubles in real terms?',
      answer: 18,
      tol: 0.5,
      unit: ' years',
      format: 'Answer as a number, e.g. 9',
      work: [
        { label: 'Toll increase each year', value: '+6%' },
        { label: 'Inflation each year', value: '(2%)', running: 'real growth 4%' },
        { label: 'Rule of 72: 72 divided by 4', value: '18 years', running: 'doubles in about 18 years' },
      ],
      why: 'A price rise only makes you richer to the extent it beats inflation. The toll doubles in about twelve years in cash terms and in about eighteen in what that cash can buy.',
      rule: 'A growth rate quoted in dollars is not a growth rate in things; subtract inflation before you use it for anything.',
    },
    {
      shell: 'S14',
      kind: 'mc',
      stem: "A hotel group's revenue rose from $500 million to $600 million and net income from $40 million to $50 million, while cash from operations fell from $70 million to $55 million. Which working capital line moved, and which way?",
      choices: [
        'Receivables rose, so sales outran collections',
        'Receivables fell, so collections outran sales',
        'Payables rose, so suppliers funded the growth',
      ],
      answer: 0,
      why: 'Profit grew and cash shrank, so the gap sits between making the sale and banking it. Growing receivables mean the guests were served and the revenue booked while the money is still with the customer.',
      traps: {
        1: 'You picked this if you flipped the sign; receivables falling means you collected old bills, which puts cash in rather than taking it out.',
        2: 'You picked this if you think unpaid supplier bills drain cash; owing more keeps cash in the account for longer.',
      },
      rule: 'When profit rises and cash falls, look first at what your customers still owe you.',
    },
    {
      shell: 'S15',
      kind: 'mc',
      stem: 'You are comparing two gas pipelines with very different debt loads and heavy, genuine spending to keep the steel in the ground working. Which multiple do you lead with?',
      choices: [
        'EV/EBIT, because depreciation here is a real cost',
        'EV/EBITDA, because it is the standard workhorse multiple',
        'P/E, because the bottom line is what owners keep',
      ],
      answer: 0,
      why: 'Depreciation on a pipeline is an estimate of a replacement bill that genuinely arrives, so charging the company for it keeps the comparison honest. Using enterprise value over a pre-interest profit also neutralises the different debt loads.',
      traps: {
        1: 'You picked this if you reach for EV/EBITDA out of habit; it prices the business as though the steel never wears out.',
        2: 'You picked this if you compare P/E across different debt loads; leverage moves P/E for reasons that have nothing to do with the pipe.',
      },
      rule: 'When capital spending is heavy and real, charge the company for it and use EV/EBIT.',
    },
    {
      shell: 'S16',
      kind: 'mc',
      stem: "Long rates rise a point. A data centre landlord's sites open in ten years; a toll road collects its cash today; a water utility pays a steady dividend. Which share price falls hardest?",
      choices: [
        'The data centre landlord, whose cash arrives latest',
        "The toll road, which collects cash in today's money",
        'The water utility, whose dividend now looks less attractive',
      ],
      answer: 0,
      why: 'A higher discount rate compounds over every year you wait, so the further out the cash sits, the more of its present value disappears. Cash collected this year is discounted once; cash a decade away is discounted ten times over.',
      traps: {
        1: 'You picked this if you assume near-term cash flows discount hardest; cash arriving this year is barely discounted at all.',
        2: 'You picked this if you stop at the bond-proxy story; a yield re-rating hurts, but it hurts less than a decade of extra discounting.',
      },
      rule: 'The longer you wait for the cash, the more a rate rise takes off its value today.',
    },

    /* ---------------- reason ---------------- */
    {
      shell: 'S17',
      kind: 'open',
      stem: 'Pick one to own for twenty years: a regulated water utility, or a landlord who leases data centre space. Which, and why?',
      tests: 'Whether you commit to one and defend it with a mechanism, instead of listing traits of both.',
      clarify: [
        'Is the utility allowed to earn a set return on its asset base, or is that return reset every few years?',
        'Is the data centre space let on long leases, or re-let every year?',
      ],
      skeleton: [
        'Say which one you would own before you explain anything.',
        'Name the moat in each: a licence against switching costs and location.',
        'Ask who sets the return, a regulator or a customer.',
        'Compare how much capital each needs and who funds it.',
        'Name the one condition that would flip your answer.',
      ],
      criteria: [
        'Said which one you would own before listing any traits',
        "Named the regulator as the thing that caps the utility's returns",
        "Named switching costs or location as the landlord's moat",
        'Named one specific condition that would change your answer',
      ],
      model:
        "I would take the data centre landlord. Both have real moats, but different people set the returns. The utility's moat is a licence: nobody else may lay the pipes, which is about as durable as a barrier gets, but the same regulator that grants it decides what I am allowed to earn, so my return is settled by a political process rather than by demand. The landlord's moat is switching costs and location: a tenant who has installed its equipment in my building does not move over a small rent increase, so I can raise the price and watch whether anyone leaves. That is a live test of pricing power, and the utility never gets to run one. The weakness in my answer is capital. Building this space costs a great deal, and new supply tends to arrive exactly when returns look good, whereas nobody builds a second water network. If leases turned over every year against plenty of new local supply, I would switch.",
      follows: [
        'What would the regulator have to do to change your mind?',
        'Would you rather own the building or run the servers inside it?',
        'How would you test whether those switching costs are real?',
      ],
      flags: [
        'Listing features of both and never choosing one.',
        'Treating "regulated" as safe without asking who sets the return.',
        'Claiming a moat without naming what a customer gives up by leaving.',
      ],
      rule: 'Name who sets the returns before you call a protected business a good one.',
    },
    {
      shell: 'S18',
      kind: 'open',
      stem: 'A wind farm operator has shown a profit in each of the last five years, and its cash balance has fallen in every one of them. How does that happen?',
      tests: 'Whether accrual accounting is a working intuition for you or a definition you memorised.',
      clarify: [
        'Is it building new turbines, or only running the ones it has?',
        'Has it been repaying loan principal over those five years?',
      ],
      skeleton: [
        'Start at the root: profit is accrual, cash is the bank account.',
        'Take the biggest candidate first: spending on turbines above the depreciation charge.',
        'Then working capital: money owed to it growing faster than sales.',
        'Then loan principal, which never reaches the income statement.',
        'Say which you would check first and where you would look.',
      ],
      criteria: [
        'Said that profit is measured on accruals and cash is not',
        'Named capital spending running above the depreciation charge',
        'Named loan principal as invisible to the income statement',
        'Said you would compare cash from operations to net income across years',
      ],
      model:
        'Profit is counted when things are earned and used up, and cash is counted when the bank moves, so the two can pull apart for years. For a wind farm I would look at capital spending first. Building or replacing turbines takes the money out immediately, while the income statement is charged only a slice of it each year as depreciation, so if it spends more than it depreciates, profit holds up and the balance falls. Second, working capital: if the money owed to it grows faster than sales, it has booked revenue it has not banked. Third, loan principal. Repaying a loan never touches the income statement at all, only the interest does, so a profitable company can still be handing its cash to lenders. What I would actually do is put cash from operations next to net income for five years. The weakness in that check is that one heavy building year is normal, so I want the pattern rather than a single year.',
      follows: [
        'Which of those would worry you most as an owner?',
        'How would you fix it if you ran the company?',
        'Where in the three statements would you find the principal repayments?',
      ],
      flags: [
        'Naming a cause without saying which direction it pushes the cash.',
        'Never mentioning that spending on assets and depreciating them happen at different times.',
        'Blaming the accounting instead of naming which cash actually left.',
      ],
      rule: 'When profit and cash disagree for years, find the spending the income statement has not been charged for yet.',
    },
    {
      shell: 'S19',
      kind: 'open',
      stem: 'There is a toll road on the edge of town and no listed company anything like it. How would you put a value on it?',
      tests: 'Whether valuation survives contact with an asset that has no comparables and no analysts.',
      clarify: [
        'Do I own the road outright, or hold it for a fixed number of years?',
        'Do I set the toll, or does a regulator cap what I can charge?',
      ],
      skeleton: [
        'Say what you are buying: a stream of tolls, for a stated length of time.',
        'Build the cash flow from traffic times toll, less a thin running cost.',
        'Discount it, and say the discount rate does most of the work.',
        'Cross-check against what similar assets sold for and what a rival road would cost to build.',
        'Name the two inputs that decide the answer, and give a range.',
      ],
      criteria: [
        'Asked whether the road is owned outright or held for a fixed term',
        'Built the value from traffic and toll rather than from a multiple alone',
        'Said the discount rate moves the answer more than the forecast does',
        'Named at least one cross-check beyond the discounted cash flow',
      ],
      model:
        'First I would ask what I am actually buying, because a road I own forever and a road I hold for twenty years are different assets, and the second is a finite stream I can nearly add up. Then I would build the cash flow from the two things that drive it: how many vehicles cross, and what each one pays. Running costs are small and mostly fixed, so nearly every extra vehicle is profit, and tolls usually rise with inflation. I would discount that stream at a rate that reflects how certain the traffic is, and I would say out loud that the discount rate does more work than my forecast does, so I would give a range instead of one number. Then two cross-checks: what similar assets have changed hands at, and what it would cost to build a competing route, since that caps what any rational buyer pays. The weakness is traffic. My whole answer rests on a guess about how many cars turn up in year fifteen.',
      follows: [
        'What would a new road nearby do to your number?',
        'Which of your inputs would you stress first?',
        'How does your answer change if the toll is capped by a regulator?',
      ],
      flags: [
        'Reaching for a discounted cash flow before asking how long you own the road.',
        'Giving one precise number when every input is a guess.',
        'Forgetting that the cost of building a rival route caps the value.',
      ],
      rule: 'Say what you are buying and for how long before you discount a single dollar.',
    },
    {
      shell: 'S20',
      kind: 'open',
      stem: 'A regional airport borrowed at a floating rate and then swapped it to fixed. Explain to me what it did and why.',
      tests: 'Whether you explain the motive and the mechanism, rather than reciting what a swap is.',
      clarify: [
        "Is the airport's own revenue fixed by contract, or does it move with traffic?",
        'Did it swap the whole loan, or only part of it?',
      ],
      skeleton: [
        'Say the exposure first: the interest bill moves and the revenue does not.',
        'Describe the swap plainly: an exchange of one payment stream for another.',
        'Say who pays what, and how the floating leg cancels out.',
        'Name what was actually bought: certainty, not a lower rate.',
        'Name the cost: if rates fall, it still pays the fixed rate.',
      ],
      criteria: [
        'Said the exposure was a floating interest bill against steadier revenue',
        'Described the swap as exchanging one stream of payments for another',
        'Said the airport bought certainty rather than a cheaper rate',
        'Named what goes wrong for the airport if rates fall afterwards',
      ],
      model:
        'Start with the problem rather than the product. The airport borrowed at a floating rate, so its interest bill moves with the market, while its landing fees and its retail rents are set for long stretches. That mismatch means a rate rise lands straight on profit with nothing on the revenue side to offset it. A swap is an exchange of payment streams: the airport agrees to pay a fixed rate to a counterparty and to receive a floating rate back. The floating receipt cancels the floating payment on the loan, so what it is left with is a fixed interest bill it can budget around. The important part is what it bought, which is certainty and not cheapness. If rates fall it is still paying the fixed rate and it will look like a bad trade, but it did not make a bet, it removed one. The real cost is that the swap is a private contract, so it now depends on the counterparty still being there.',
      follows: [
        'What happens to the airport if rates fall two points?',
        'Who is on the other side of this swap, and why would they take it?',
        'Would you rather it had done nothing at all?',
      ],
      flags: [
        'Explaining the mechanics with no reason for doing the trade.',
        'Calling the swap a bet on rates rather than the removal of one.',
        'Forgetting that a private contract carries counterparty risk.',
      ],
      rule: 'A hedge buys you a known number, not a better one; say which exposure it cancels.',
    },
  ],
}
