import type { PracticeTest } from './types'

export const TEST_2: PracticeTest = {
  id: 't2',
  n: 2,
  title: 'Steel in the Ground',
  blurb:
    'Twenty questions on capital-heavy businesses, worked at interview pace: answer out loud first, then check what the reasoning was supposed to be.',
  items: [
    /* ---------- recall ---------- */
    {
      shell: 'S01',
      kind: 'mc',
      stem: 'You want to know what a warehouse operator owned and owed on 31 December. Which report answers that?',
      choices: [
        'The income statement, a summary of the year',
        'The balance sheet, a snapshot of one day',
        "The cash flow statement, the year's bank movement",
      ],
      answer: 1,
      why: 'Only the balance sheet lists what the business holds and what is claimed against it, and it describes a single date rather than a stretch of time. Take it again a week later and every line can differ.',
      traps: {
        0: 'You picked this if you are reading the income statement as a status report; it adds up a whole year of trading and never says what is owned at the end.',
        2: 'You picked this if you are treating the bank balance as the full picture; the cash flow statement covers a period and only tracks cash, not racking, trucks, or debt.',
      },
      rule: 'The balance sheet is a photograph of one day; the other two cover a stretch of time.',
    },
    {
      shell: 'S02',
      kind: 'mc',
      stem: 'A trucking fleet hauls a load in March and bills the shipper, who pays the invoice in June. When does the revenue count?',
      choices: [
        'In March, when the load was actually hauled',
        "In June, when the shipper's payment finally arrives",
        'Split across March and June by payment terms',
      ],
      answer: 0,
      why: 'You earned the money the moment you delivered the load, so that is the period it belongs to. The June payment is a separate event and it shows up on the cash flow statement instead.',
      traps: {
        1: 'You picked this if you are booking revenue when cash lands; that is cash accounting, and it is exactly the gap the cash flow statement exists to close.',
        2: 'You picked this if you think revenue is spread to match the collection schedule; the split is between earning and collecting, not between two months.',
      },
      rule: 'You book a sale when you deliver the service, not when the money reaches the bank.',
    },
    {
      shell: 'S03',
      kind: 'mc',
      stem: 'You want to judge how well a construction equipment dealer is run, setting aside how much debt it carries. Which margin do you read?',
      choices: [
        'Gross margin, which is after direct product cost',
        'Operating margin, which is after running the company',
        'Net margin, which is after interest and tax',
      ],
      answer: 1,
      why: 'Operating margin absorbs every cost of running the dealership but stops above interest, so two dealers run identically with different loan books show the same number. That is what makes it the line for judging operations.',
      traps: {
        0: 'You picked this if you are judging the product rather than the operation; gross margin stops before wages, rent, and the yard, so a badly run dealer can still show a fine one.',
        2: 'You picked this if you forgot net margin sits below interest, which is precisely the debt load you said you wanted to set aside.',
      },
      rule: 'Gross margin judges the product, operating margin judges the business, net margin judges the financing too.',
    },
    {
      shell: 'S04',
      kind: 'mc',
      stem: 'A rail freight operator runs the only line into a mining region. Traffic there would not cover the cost of a second line. Which moat is that?',
      choices: [
        'Efficient scale, since the market supports one player',
        'Network effects, since each shipper helps the others',
        'Switching costs, since shippers pay to change carriers',
      ],
      answer: 0,
      why: 'The barrier is the size of the prize, not anything the incumbent does. A rival that built alongside would split the same traffic and neither operator would cover its capital, so nobody rational enters.',
      traps: {
        1: 'You picked this if you call any shared infrastructure a network; an extra shipper on this line makes it no more valuable to the shippers already using it.',
        2: 'You picked this if you read "no alternative" as a switching cost; the barrier here is that no rival would build, not what it costs a shipper to leave.',
      },
      rule: 'When a market is too small for a second entrant to earn a return, the moat is efficient scale.',
    },
    {
      shell: 'S05',
      kind: 'mc',
      stem: 'A shipping line earns 14% on its invested capital while that capital costs 9%. It plans to order a fleet of new vessels. What does that growth do?',
      choices: [
        'It creates value faster, since each vessel earns above its cost',
        'It destroys value, because a bigger fleet needs so much capital',
        'It leaves value unchanged, since growth is separate from returns',
      ],
      answer: 0,
      why: 'Every dollar put into a new vessel is funded at nine cents and returns fourteen, so reinvestment gains five cents a year. Growth multiplies whatever spread you already earn, in whichever direction it points.',
      traps: {
        1: 'You picked this if you read a heavy capital requirement as value destruction; what matters is the return that capital earns against its cost, not how much of it there is.',
        2: 'You picked this if you treat growth as value-neutral; growth is the volume dial on the spread between return and cost, not a separate question.',
      },
      rule: 'Growth is only worth funding once the return on capital clears the cost of that capital.',
    },
    {
      shell: 'S06',
      kind: 'mc',
      stem: 'Two airlines run identical fleets and carry the same market capitalisation. One owes $3B to its lenders and the other owes nothing. Which costs more to own outright?',
      choices: [
        'The levered airline, since the buyer inherits its debt',
        'The debt-free airline, since debt cuts the effective price',
        'Neither, since their market values are identical today',
      ],
      answer: 0,
      why: 'Owning the operations outright means clearing every claim on them, and the lenders hold one. You pay the same market capitalisation to shareholders either way, then settle $3B more on the levered airline, so its enterprise value is $3B higher.',
      traps: {
        1: 'You picked this if you are subtracting debt the way you subtract cash; cash you receive and take off the price, debt you assume and add on.',
        2: 'You picked this if you stopped at market capitalisation; that prices the shares, and the lenders still have to be paid out of the same assets.',
      },
      rule: 'Debt travels with the company you buy, so equal market caps can mean very unequal prices.',
    },
    {
      shell: 'S07',
      kind: 'mc',
      stem: 'The risk-free rate is 4%, the equity risk premium is 5%, and a trucking company has a beta of 1.2. What return do its shareholders require?',
      choices: ['6%', '9%', '10%'],
      answer: 2,
      why: 'CAPM starts at the risk-free 4%, the floor under every expected return, then pays you for market risk alone: 1.2 times the 5% premium is 6 points. Together that is a 10% cost of equity.',
      traps: {
        0: 'You picked this if you multiplied beta by the premium and stopped; the risk-free rate is the base every expected return is built on, not an optional extra.',
        1: 'You picked this if you added the 5% premium straight on without multiplying it by beta; beta is what scales the market premium to this particular company.',
      },
      rule: 'Build a cost of equity from the risk-free rate up, then add beta times the equity risk premium.',
    },
    {
      shell: 'S08',
      kind: 'mc',
      stem: 'An airline pays a premium for a call option on jet fuel. Fuel then falls well below the strike price. What happens to the airline?',
      choices: [
        'It lets the option expire and loses the premium',
        'It must buy at the strike and take the loss',
        'It owes the seller the difference from the strike',
      ],
      answer: 0,
      why: 'A call is a right, so the buyer simply walks away when exercising would be worse than the market. The premium already paid is the whole of the downside, however far fuel falls.',
      traps: {
        1: 'You picked this if you are treating an option as an obligation; that is a future or a forward, where both sides must transact at the agreed price.',
        2: "You picked this if you are settling it like a future, where the party on the wrong side of the price pays the difference; an option only ever pays from seller to buyer, and the buyer's outlay stops at the premium.",
      },
      rule: 'As the buyer of an option your loss stops at the premium; your gain does not.',
    },

    /* ---------- apply ---------- */
    {
      shell: 'S09',
      kind: 'num',
      stem: "A parts manufacturer's depreciation rises by $40M. The tax rate is 25% and nothing else changes. By how much does cash at the end of the year change, in $M?",
      answer: 10,
      unit: '$M',
      format: 'Answer as a number, e.g. 6. A rise in cash is positive.',
      work: [
        { label: 'Extra depreciation charged on the income statement', value: '($40M)', running: 'operating profit -$40M' },
        { label: 'Tax saved on that charge at 25%', value: '+$10M', running: 'net income -$30M' },
        { label: 'Cash flow statement starts at net income', value: '($30M)', running: '-$30M' },
        { label: 'Add back the charge, since no money moved', value: '+$40M', running: 'cash +$10M' },
      ],
      why: 'The charge itself never touched the bank account, but the tax it saves is real money that stayed with you. That is why a larger paper cost can leave a company holding more cash.',
      rule: 'A non-cash charge lowers profit but raises cash by exactly the tax it saves.',
    },
    {
      shell: 'S10',
      kind: 'num',
      stem: 'A trucking fleet reports net income of $5M. Depreciation was $3M. Receivables rose $2M, spare-parts inventory rose $1M, and payables rose $1M. What was cash from operations, in $M?',
      answer: 6,
      unit: '$M',
      format: 'Answer as a number, e.g. 9',
      work: [
        { label: 'Net income, straight off the income statement', value: '+$5M', running: '$5M' },
        { label: 'Add back depreciation, no money left the bank', value: '+$3M', running: '$8M' },
        { label: 'Receivables up $2M: hauled, billed, not collected', value: '($2M)', running: '$6M' },
        { label: 'Spare parts up $1M: paid for, still on the shelf', value: '($1M)', running: '$5M' },
        { label: 'Payables up $1M: suppliers not yet paid', value: '+$1M', running: '$6M' },
      ],
      why: 'Profit counts what you earned; cash counts what settled. Every dollar sitting in an unpaid invoice or a shelf of spare parts is profit you cannot spend yet.',
      rule: 'A rise in receivables or inventory is cash out; a rise in payables is cash you still hold.',
    },
    {
      shell: 'S11',
      kind: 'num',
      stem: 'A construction equipment dealer has 40M shares at $20, debt of $300M, and cash of $100M. EBITDA is $100M. What is its EV/EBITDA multiple?',
      answer: 10,
      unit: 'x',
      format: 'Answer as a number, e.g. 7',
      work: [
        { label: 'Equity value: 40M shares at $20', value: '+$800M', running: '$800M' },
        { label: 'Add debt, a claim on the same assets', value: '+$300M', running: '$1,100M' },
        { label: 'Subtract cash, which you receive on purchase', value: '($100M)', running: 'EV $1,000M' },
        { label: 'Enterprise value over EBITDA of $100M', value: '10.0x' },
      ],
      why: 'The numerator and denominator have to describe the same claim. Enterprise value is the price of the whole operation, so it belongs over a profit measured before interest, while market cap belongs over earnings after it.',
      rule: 'The top and the bottom of a multiple must belong to the same claimants, or you are comparing nothing.',
    },
    {
      shell: 'S12',
      kind: 'num',
      stem: 'A rail freight operator charges $600 to move one container and spends $250 of variable cost doing it. Fixed costs run $700,000 a month. How many containers a month break even?',
      answer: 2000,
      format: 'Answer as a number, e.g. 1500',
      work: [
        { label: 'Price charged per container', value: '+$600' },
        { label: 'Variable cost per container', value: '($250)', running: 'contribution $350' },
        { label: 'Monthly fixed costs to cover', value: '($700,000)' },
        { label: 'Fixed costs divided by $350 of contribution', value: '2,000 containers' },
      ],
      why: 'Every container past the two-thousandth adds $350 straight to profit, because the fixed costs are already paid. That is operating leverage, and it works just as hard against you below the line.',
      rule: 'Breakeven is fixed costs divided by the profit each unit contributes, never by its price.',
    },
    {
      shell: 'S13',
      kind: 'num',
      stem: "A shipping line's freight rates are rising 15% a year while inflation runs 3%. Using the rule of 72, roughly how many years until rates double in real terms?",
      answer: 6,
      tol: 0.5,
      unit: ' years',
      format: 'Answer as a number, e.g. 9',
      work: [
        { label: 'Nominal rise in freight rates', value: '+15%' },
        { label: 'Less inflation over the same period', value: '(3%)', running: 'real growth +12%' },
        { label: 'Rule of 72: divide 72 by the real rate', value: '72 / 12', running: '6 years' },
      ],
      why: 'Doubling the price you charge is not doubling what that price buys. Strip inflation out first, or you will credit yourself with growth the price level already ate.',
      rule: 'Take inflation out before you compound, then divide 72 by whatever is left.',
    },
    {
      shell: 'S14',
      kind: 'mc',
      stem: "A parts manufacturer pays cash for a $60M stamping press that will last ten years. Which line of this year's cash flow statement carries the full $60M?",
      choices: [
        'Cash from operations, since the press is a cost',
        'Cash used in investing, since the press is equipment',
        'Cash from financing, since the press lasts many years',
      ],
      answer: 1,
      why: 'Buying an asset that lasts years is an investing outflow, and it leaves in full this year. The income statement never sees the $60M at all; it sees one slice of it a year as depreciation.',
      traps: {
        0: 'You picked this if you are routing capital spending through operating; operations carry the running of the business, not the purchase of the machines it runs on.',
        2: 'You picked this if you read "long-lived" as financing; financing tracks money coming from owners and lenders, not what the company spends it on.',
      },
      rule: 'Buying equipment is an investing outflow, whatever the income statement shows that year.',
    },
    {
      shell: 'S15',
      kind: 'mc',
      stem: 'A warehouse operator spends heavily each year on racking and forklifts that genuinely wear out. Which multiple compares it fairly with its peers?',
      choices: [
        'EV/EBITDA, the usual workhorse for comparing operating businesses',
        'EV/EBIT, which charges the company for assets consumed',
        'P/E, which reflects the earnings shareholders actually keep',
      ],
      answer: 1,
      why: 'Here depreciation is a real bill arriving later, not an accounting quirk, because the forklifts do have to be replaced. Charging for it keeps the comparison honest between operators who consume their kit at different rates.',
      traps: {
        0: 'You picked this if EV/EBITDA is your default multiple; it pretends capital spending does not exist, which flatters exactly this kind of business.',
        2: 'You picked this if you reached for P/E without noticing it sits below interest, so two identical warehouses with different debt would look like different businesses.',
      },
      rule: 'When capital spending is heavy and real, step down the ladder from EBITDA to EBIT.',
    },
    {
      shell: 'S16',
      kind: 'mc',
      stem: 'Rates rise by one percentage point across the curve. You hold a thirty-year bond issued by a rail operator, a two-year bond from a shipping line, and shares in a mature trucking firm generating steady cash. Which falls the most?',
      choices: [
        'The thirty-year bond, repaid furthest into the future',
        'The two-year bond, since bonds move most on rates',
        'The trucking shares, which carry the most business risk',
      ],
      answer: 0,
      why: 'Both bonds pay a fixed coupon, so the price is the only thing that can adjust to a higher market yield. The longer you wait to be repaid, the more adjusting that takes, and thirty years of it beats two.',
      traps: {
        1: 'You picked this if you stopped at the word bond without asking how long you wait for the money; two years is repaid before much damage can build up.',
        2: 'You picked this if you ranked by how risky each business feels; a rate move prices when the cash arrives, not how solid the operation is.',
      },
      rule: 'How long you wait for the money, not the label on the asset, decides who a rate rise hurts.',
    },

    /* ---------- reason ---------- */
    {
      shell: 'S17',
      kind: 'open',
      stem: 'Would you rather own a construction equipment dealer, or the manufacturer whose machines it sells?',
      tests: 'Whether you can locate where the pricing power sits instead of listing features of both sides.',
      clarify: [
        'Does the dealer hold an exclusive territory, or does it compete with other dealers nearby?',
        'Am I buying the two at the same price, or is one of them cheaper?',
      ],
      skeleton: [
        'Say the frame first: where the scarce asset sits and who can raise price.',
        'Walk the dealer through the frame: what it owns, and what it earns after the sale.',
        'Walk the manufacturer through the same frame, and name what it owns that the dealer does not.',
        'Test each for a moat: can the customer switch cheaply, and can a rival enter?',
        'Name the shared risk, since both sell equipment that customers buy on credit.',
        'Commit to one, and name the fact that would flip you.',
      ],
      criteria: [
        'Named the parts and service stream, not only the sale of machines',
        'Said whether the territory is exclusive and why that decides the answer',
        'Said the manufacturer carries the factories and the dealer does not',
        'Committed to one side and named a specific fact that would change your mind',
      ],
      model:
        "I would take the dealer, provided the territory is exclusive. The manufacturer owns the engineering and the brand, but it also owns the factories, and a plant sized for a good year is a punishing fixed cost in a bad one. The dealer ties up far less capital and earns twice: once on the machine, then for years on parts and service, which the customer cannot easily buy elsewhere because the machine is already sitting in his yard. That is a switching cost, and it should show up as steadier margins through the cycle. The weakness in my answer is that the dealer's whole position is granted by the manufacturer. If the territory can be split or withdrawn, my moat is somebody else's contract and the manufacturer takes the value back. So I would want the length of that agreement before committing, and a short one would flip me to the manufacturer.",
      follows: [
        'What happens to each of them in a construction downturn?',
        'How would you check whether the parts business is really protected?',
        'Would your answer change if the manufacturer sold direct to customers?',
      ],
      flags: [
        'Listing pros and cons of both and never picking one.',
        'Talking only about machine sales and missing the aftermarket entirely.',
        'Calling the brand a moat without saying what stops a customer switching.',
      ],
      rule: 'Ask where the scarce asset sits and who can raise price, then commit with one named weakness.',
    },
    {
      shell: 'S18',
      kind: 'open',
      stem: 'A trucking fleet has been profitable every quarter for three years and is about to miss payroll. How?',
      tests: 'Whether accrual accounting is intuition for you rather than a definition you can recite.',
      clarify: [
        'Is the fleet growing, or has revenue been roughly flat?',
        'Is it repaying loan principal, or only paying interest on the debt?',
      ],
      skeleton: [
        'Name the root cause first: profit is accrual, cash is not.',
        'Working capital: shippers pay in sixty days while fuel and drivers are paid weekly.',
        'Capital spending above depreciation: a new tractor costs more than the charge on the old one.',
        'Debt principal, which never appears on the income statement at all.',
        'Say which of these you would check first, and in which statement.',
      ],
      criteria: [
        'Said revenue is booked when the load is delivered, not when the invoice is paid',
        'Named growing receivables or inventory as cash consumed by growth',
        'Named at least one outflow that never touches the income statement',
        'Said you would compare cash from operations with net income across several years',
      ],
      model:
        "Profit is booked when the load is delivered and cash arrives when the shipper pays, so the two can drift apart for years. If the fleet is growing, every new lane consumes cash before it produces any: I pay drivers weekly and fuel daily while the shipper pays me in sixty days, so receivables grow faster than revenue. Second, the trucks. Depreciation charges the old fleet at what it cost years ago, while replacing a tractor costs today's price, so real spending runs above the accounting charge. Third, loan principal never touches the income statement, only the interest does, and the principal still has to be paid. I would go to the cash flow statement and compare cash from operations with net income over three years. The weakness in that check is that it tells me where the cash went, not whether the cause is a growth problem or a collections problem.",
      follows: [
        'Which of those three would worry you most as an owner?',
        'How would you fix it if you ran the company on Monday?',
        'What would you expect the cash conversion cycle to look like here?',
      ],
      flags: [
        'Saying "receivables" and stopping there.',
        'Treating it as fraud rather than as ordinary accrual timing.',
        'Never naming a single outflow that skips the income statement.',
      ],
      rule: 'A growing business books each sale before it collects it, so growth and a cash squeeze arrive together.',
    },
    {
      shell: 'S19',
      kind: 'open',
      stem: 'A family wants to sell you its haulage yard: one depot, twelve trucks, no public comparables and nobody who follows it. Put a number on it.',
      tests: 'Whether you build a defensible number out of assumptions you say out loud, instead of stalling for data that does not exist.',
      clarify: [
        'Am I buying the trucks and the yard itself, or only the business and its shipper contracts?',
        'Do the parents drive and dispatch themselves, and would they stay on after the sale?',
      ],
      skeleton: [
        'Say what I am buying: the contracts, the trucks, the yard, and the customer list.',
        'Normalise the profit: take the family wages out and put a hired manager back in.',
        'Pick a multiple, say why that level, and read out the range it gives.',
        'Cross-check against replacement cost: what twelve trucks and a yard cost to assemble.',
        'Sit high or low inside my range depending on how fragile the revenue looks.',
        'Name the assumption that would move the number most.',
      ],
      criteria: [
        'Replaced the family wages with a market wage before applying any multiple',
        'Named a specific multiple and said why that level rather than another',
        'Cross-checked the answer against replacement cost or the value of the assets',
        'Gave a range with two numbers in it rather than one point estimate',
      ],
      model:
        "I would value the cash flow and then check it against the metal. Say the yard reports $900,000 of profit, but the two parents draw $50,000 each and a hired manager would cost $150,000, so normalised profit is nearer $850,000. I am buying a business, not a job. For a one-depot operator with no comparables I would pay a low multiple, three to five times, because the cash flows are fragile and I could not sell this quickly. That gives me roughly $2.5m to $4.25m. As a cross-check, twelve trucks and a yard might cost $3m to assemble from scratch, so the bottom of my range is close to asset value and I am paying almost nothing there for the customer relationships. I would sit near that bottom if three shippers are most of the revenue. The weakness is that my multiple is asserted, not observed, because I have no comparable sale to anchor it to.",
      follows: [
        'Which of your two checks would you trust more, and why?',
        'What would you pay if the parents signed on for three more years?',
        'What single number would you demand to see before you signed?',
      ],
      flags: [
        'Asking for comparables and stalling once told there are none.',
        'Applying a multiple without ever normalising the owner pay.',
        'Naming one number with no range and no assumption underneath it.',
      ],
      rule: 'With no comparables, normalise the earnings, pick a multiple you can defend, and quote a range instead of a point.',
    },
    {
      shell: 'S20',
      kind: 'open',
      stem: "A shipping line locks in next year's fuel price using futures. Explain to a friend with no finance background what it has done and what could go wrong.",
      tests: 'Whether you can teach a mechanism, and whether you know a hedge costs cash before it pays anything.',
      clarify: [
        'Does the shipping line pass fuel costs through to customers in its contracts?',
        'Are these exchange-traded futures, or a private forward with one bank?',
      ],
      skeleton: [
        'Give the shape before the vocabulary: an agreement to buy at a set price on a set date.',
        'One concrete example with numbers, walked in both directions.',
        'Say what makes it a hedge: it offsets fuel the line already has to buy.',
        'Name the mechanism that matters: daily settlement and margin posted to the exchange.',
        'Name what goes wrong: margin calls, and being locked in when fuel falls.',
      ],
      criteria: [
        'Said the futures contract is an obligation, not a right to walk away',
        'Walked the payoff in both directions, not only the one that helps',
        'Named daily mark-to-market or margin as the mechanical point of a future',
        'Named a real cost: a margin call, or being locked above a falling fuel price',
      ],
      model:
        "They have agreed today to buy fuel next year at a fixed price, and unlike an option it is an agreement both sides must honour. Say fuel is $600 a tonne and they lock next year at $620. If fuel goes to $800 they still pay $620 and the contract has saved them $180 a tonne. If fuel falls to $500 they still pay $620 and they have lost $120, which is the price of certainty. That is what makes it a hedge rather than a bet: they already have to buy the fuel, so the contract cancels a swing they were exposed to either way. The mechanism people miss is that a future settles every day through an exchange, with cash posted as margin. So a position that ends up right can still demand cash along the way, and those margin calls arrive exactly when fuel has moved against them and cash is tightest.",
      follows: [
        'Why might their treasurer prefer a private forward instead?',
        'If a fund with no ships bought the same contract, what would it be doing?',
        'What would you want to know before calling this a good decision?',
      ],
      flags: [
        'Leading with jargon instead of the shape of the agreement.',
        'Only walking the case where fuel rises and the hedge looks clever.',
        'Saying futures are exchange-traded and stopping, when daily settlement is the point.',
      ],
      rule: 'A hedge is judged against the exposure you already carry, and it demands cash before it pays out.',
    },
  ],
}
